version: '3'
services:
  web:
    container_name: razvanescu-compose-frontend-2.0
    image: razvanescu/frontend-compose-dev2:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - /app/node_modules
      - .:/app
  tests:
    container_name: razvanescu-compose-frontend-test-2.0
    image: razvanescu/frontend-compose-test-dev2:1.0
    build:
      context: .
      dockerfile: Dockerfile.dev
    volumes:
      - /app/node_modules
      - .:/app
    command: ["npm","run","test"]